### ISSUE TITLE
Import buildings, rooms, and saunas from student village

### ISSUE THREAD

**Issue by rkdarst** [usefulaaltomap/usefulaaltomap#27]

**Comment by rkdarst** [comment]
@wno-git, I just added most of the buildings (that I found from OSM), in commit 1d2411267b.  They are searchable, but not highlighted by default.  I used abbreviations SMT, JMV, OK, SK, and OR.  In particular, are SK and OR correct?

There's stuff inside the buildings which could be imported.  Also some of the street addresses could use clarifications (e.g. SMT12,JMV11 on OSM, JMT11 labels on usefulaaltomap).  JMV3,5 have a lot of different segments and I'm not sure which need to be mapped, ...

Thoughts?

**Comment by wno-git** [comment]
The abbreviation for Jämeräntaival is not correct. It should be **JMT**. The others look correct to me.

As for the segments, the segments tagged JMT3{a,b,c} are the apartment buildings. The other segments are corridors between the buildings or common areas. Same applies for JMT5{a,b,c}. JMT7 also has a corridor between the buildings A and C but it's missing from OSM.

**Comment by rkdarst** [comment]
OK, thanks.  I've corrected the abbreviations and some about those buildings.

Next up, adding all the other features of the student village...
