### ISSUE TITLE
Wiki could add information about development environment

### ISSUE THREAD

**Issue by josephguillaume** [usefulaaltomap/usefulaaltomap#36]
### Setting up development environment
* Ensure `python3 `and `make `are on your path. Edit the makefile to set the name of the python executable if necessary.
* `pip install pyyaml`

To run:
* When using Git Bash on Windows, you may need to set: `export PYTHONIOENCODING="utf_8"`
* `make` to compile data
* `python -m http.server`
* Open your browser: http://127.0.0.1:8000/

**Comment by wno-git** [comment]
First step of making the development environment reproducible and easier to set up would be to record the library dependencies of the application. I opened #38 regarding this. Also, virtualenv allows setting up the dependencies in a self-contained environment.

After this change the steps to install the dependencies of the application would be:
 * `virtualenv -p python3 env`
 * `source env/bin/activate`
 * `pip install -r requirements.txt`

Then compiling the data (in the shell where the virtualenv is active):
 * `make`

**Comment by rkdarst** [comment]
Added here: https://github.com/usefulaaltomap/usefulaaltomap/wiki/Code-development

Thanks!
