### ISSUE TITLE
Entrances which aren't on the building outline aren't included

### ISSUE THREAD

**Issue by rkdarst** [usefulaaltomap/usefulaaltomap#39]
A Grid and Aalto Studios have this for their main entrances: they are under a covered entryway.

I think easiest solution is to either add an explicit list of extra entrances for the data, or be able to specify multiple outlines for entrances.

**Comment by josephguillaume** [comment]
The more complex solution would be to detect building:part (using spatial overlay operations) and include entrances on those?
I don't know if there would be any cases of 'internal' entrances between building parts though.

I don't think it would make sense to specify arbitrary additional outlines for entrances, so adding explicit entrances to the data seems like a good solution. It would still need deduplication in case it's already imported (not sure how that works atm, I'm having trouble with r034-286)

**Comment by rkdarst** [comment]
Yeah, your first solution would be most general but I guess more work than it's worth.

Explicit entrances: currently entrances are found by taking building outline, and searching all nodes for any entrances, then adding them.  I would do something like add as a building attribute "also search these nodes for entrances".  Then, just add those to the iteration of the building outline (with something to prevent duplicates...).  Right now, entrances (and rooms) exist *only* in OSM, no YAML data about them.

The function may be a bit confusing, but basically is logic to decide which entrances to include or not and making the equivalent YAML data, then adding it as a child

**Comment by josephguillaume** [comment]
If you're ok with one overpass query per building, you can do it by recursion, though there might be some cases where it gives strange results.
Get nodes of building, recurse backwards from nodes to ways that are building parts, recurse forward from ways to nodes that are entrances.
Could be unioned with the entrances on the building itself.

http://overpass-turbo.eu/s/vS8

[out:json][timeout:25];
way(24342454);>; way(bn)["building:part"]; node(w)["entrance"];
out body;
out skel qt;

**Comment by rkdarst** [comment]
That's pretty good use of the overpass API, better than I could do quickly.  Though, right now there is just one query for the whole dataset, so then it would require either restructuring of how the API is used or re-doing that recursive logic in Python anyway.  I would probably do something more like the second, but if you do the first one first, great.

**Comment by josephguillaume** [comment]
Looking at the code again, the simpler solution is to download all entrances and look for enclosed entrances when processing nodes on the building
I had a first untested go (on mobile)  in enclosed_entrances branch

**Comment by josephguillaume** [comment]
Done!

Should probably include access=university too, to be consistent with the behaviour for room.
I agree with leaving off access=* - we'll just need some QA tools to keep track of which entrances need to be surveyed

There are some deeper issues that could maybe be explored later:
- I didn't think matplotlib's contain should pick up points on the outline, and the fact that it does makes it difficult to keep track of how many enclosed entrances we have, and where
- compile.py shouldn't be adding Locations with duplicate ids - we could either use sets or see if we can do more extensive merging of Location properties. I think this is causing the UI problem
